#!/usr/bin/sh

#CARDNUMBER=1
CARDNAME="Xonar"
OUTPUTNAME='Analog Output'
CARDS=$(cat /proc/asound/cards)
CARDSTRING=$(cat /proc/asound/cards | grep "${CARDNAME}")

SPEAKERSITEM='Stereo Headphones'
HEADPHONESITEM='Stereo Headphones FP'

HEADPHONES="  Item0: 'Stereo Headphones FP'"
SPEAKERS="  Item0: 'Stereo Headphones'"


setheadphones () {
  amixer -c $CARDNUMBER set "$OUTPUTNAME" "$HEADPHONESITEM" > /dev/null
}

setspeakers () {
  amixer -c $CARDNUMBER set "$OUTPUTNAME" "$SPEAKERSITEM" > /dev/null
}

check () {
  CURRENTOUTPUT="$(amixer -c $CARDNUMBER get 'Analog Output' | grep Item0:)"
}

print () {
  case ${CURRENTOUTPUT} in
    $HEADPHONES )
		  echo "🎧"
      ;;
    $SPEAKERS )
		  echo "🔉"
      ;;
  esac
}

case $CARDSTRING in
" 0 [DGX            ]: CMI8786 - Xonar DGX")
CARDNUMBER=0 ;;
" 1 [DGX            ]: CMI8786 - Xonar DGX")
CARDNUMBER=1 ;;
" 2 [DGX            ]: CMI8786 - Xonar DGX")
CARDNUMBER=2 ;;
" 3 [DGX            ]: CMI8786 - Xonar DGX")
CARDNUMBER=3 ;;
esac

check

case $BLOCK_BUTTON in
  1)   # left click
    case ${CURRENTOUTPUT} in
      $HEADPHONES )
        setspeakers
        ;;
      $SPEAKERS )
        setheadphones
        ;;
    esac
esac

check
print

